"""create spimex table

Revision ID: fc95cdcc8a0f
Revises:
Create Date: 2026-06-06 13:56:42.160773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc95cdcc8a0f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spimex_trading_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange_product_id", sa.String(), nullable=False),
        sa.Column("exchange_product_name", sa.String(length=255), nullable=False),
        sa.Column("oil_id", sa.String(), nullable=False),
        sa.Column("delivery_basis_id", sa.String(), nullable=False),
        sa.Column("delivery_basis_name", sa.String(length=255), nullable=False),
        sa.Column("delivery_type_id", sa.String(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("total", sa.Numeric(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exchange_product_id",
            "date",
            "delivery_basis_name",
            name="uniq_date_product_id",
        ),
    )
    op.create_index(
        op.f("ix_spimex_trading_results_date"),
        "spimex_trading_results",
        ["date"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_spimex_trading_results_date"),
        table_name="spimex_trading_results",
    )
    op.drop_table("spimex_trading_results")
    # ### end Alembic commands ###
