"""update spimex table

Revision ID: 29507e95fd02
Revises:
Create Date: 2026-06-06 12:30:54.229148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29507e95fd02"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_spimex_trading_results_date"),
        "spimex_trading_results",
        ["date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_spimex_trading_results_date"), table_name="spimex_trading_results"
    )
    # ### end Alembic commands ###
